---
title: "bcf"
output:
  html_document: default
  pdf_document: default
date: "2025-04-29"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(bcf)
set.seed(42)


#作者写的

# data generating process
p = 3 #two control variables and one moderator
n = 250
#
set.seed(1)
x = matrix(rnorm(n*p), nrow=n)
# create targeted selection
q = -1*(x[,1]>(x[,2])) + 1*(x[,1]<(x[,2]))
# generate treatment variable
pi = pnorm(q)
z = rbinom(n,1,pi)
# tau is the true (homogeneous) treatment effect
tau = (0.5*(x[,3] > -3/4) + 0.25*(x[,3] > 0) + 0.25*(x[,3]>3/4))
# generate the response using q, tau and z
mu = (q + tau*z)
# set the noise level relative to the expected mean function of Y
sigma = diff(range(q + tau*pi))/8
# draw the response variable with additive error
y = mu + sigma*rnorm(n)
# If you didn't know pi, you would estimate it here
pihat = pnorm(q)
bcf_fit = bcf(y, z, x, x, pihat, nburn=100, nsim=100)
# Get posterior of treatment effects
tau_post = bcf_fit$tau
tauhat = colMeans(tau_post)
plot(tau, tauhat); abline(0,1)

```



```{r}
library(bcf)
generate_data_with_Y <- function(n, homogeneous, linear) {
  p = 3
  x_mat <- matrix(rnorm(n*p), nrow=n)
  x1 <- x_mat[,1]; x2 <- x_mat[,2]; x3 <- x_mat[,3]
  x4 <- rbinom(n, 1, 0.5)
  x5 <- sample(1:3, n, replace = TRUE)#严重怀疑论文的x4和x5写反了，但老师回答说就按论文要求来
  
  if (homogeneous) {
    tau_x <- rep(3, n)
  } else {
    tau_x <- 1 + 2 * x2 * x5
  }
  
  if (linear) {
    g_x4 <- sapply(x5, function(x) if (x == 1) 2 else if (x == 2) -1 else -4)
    mu_x <- 1 + g_x4 + x1 * x3
  } else {
    g_x4 <- sapply(x5, function(x) if (x == 1) 2 else if (x == 2) -1 else -4)
    mu_x <- -6 + g_x4 + 6 * abs(x3 - 1)
  }
  
  pi_x <- 0.8 * pnorm(3 * mu_x / sd(mu_x) - 0.5 * x1) + 0.05 + runif(n) / 10
  pi_x <- pmin(pmax(pi_x, 0), 1)
  
  T <- rbinom(n, 1, pi_x)
  # enforce homogeneous effect
  tau_x <- rep(3, n)
  mu <- mu_x + tau_x * T
  sigma <- diff(range(mu_x + tau_x * pi_x)) / 8
  Y <- mu + sigma * rnorm(n)
  
  data <- data.frame(x1, x2, x3, x4, x5, mu_x, tau_x, pi_x, T, Y)
  data <- cbind(data, x_mat)  # last three columns will be V1, V2, V3
  return(data)
}


set.seed(1)
dat <- generate_data_with_Y(n = 250, homogeneous = T, linear = T) #n = 250 or 500, homogeneous = T or F, linear = T or F

# 生成数据后
x_mat <- as.matrix(dat[, c("x1", "x2", "x3","x4")]) #如果选择homogeneous = F，加上x5

y     <- dat$Y
z     <- dat$T
pihat <- dat$pi_x

library(bcf)
bcf_fit <- bcf(y, z, x_mat, x_mat, pihat,
               nburn = 100, nsim = 100)

tau_post = bcf_fit$tau
tauhat = colMeans(tau_post)
plot(tau, tauhat)
```

